// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonHostApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonHostApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonHostApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonHostApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonHostApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonHostApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct Item: Hashable {
  var id: Int64
  var title: String
  var isDone: Bool
  var isFavorite: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Item? {
    let id = pigeonVar_list[0] as! Int64
    let title = pigeonVar_list[1] as! String
    let isDone = pigeonVar_list[2] as! Bool
    let isFavorite = pigeonVar_list[3] as! Bool

    return Item(
      id: id,
      title: title,
      isDone: isDone,
      isFavorite: isFavorite
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      isDone,
      isFavorite,
    ]
  }
  static func == (lhs: Item, rhs: Item) -> Bool {
    return deepEqualsPigeonHostApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonHostApi(value: toList(), hasher: &hasher)
  }
}

private class PigeonHostApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Item.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonHostApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Item {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonHostApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonHostApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonHostApiPigeonCodecWriter(data: data)
  }
}

class PigeonHostApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonHostApiPigeonCodec(readerWriter: PigeonHostApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TaskHostApi {
  func getItems(completion: @escaping (Result<[Item], Error>) -> Void)
  func getIsFiltered() throws -> Bool
  func toggleShowAddSheet() throws
  func goToDetail(id: Int64) throws
  func toggleFavorite(id: Int64, isFavorite: Bool) throws
  func toggleDone(id: Int64, isDone: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TaskHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonHostApiPigeonCodec.shared }
  /// Sets up an instance of `TaskHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TaskHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.getItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getItemsChannel.setMessageHandler { _, reply in
        api.getItems { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getItemsChannel.setMessageHandler(nil)
    }
    let getIsFilteredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.getIsFiltered\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIsFilteredChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getIsFiltered()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIsFilteredChannel.setMessageHandler(nil)
    }
    let toggleShowAddSheetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.toggleShowAddSheet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleShowAddSheetChannel.setMessageHandler { _, reply in
        do {
          try api.toggleShowAddSheet()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toggleShowAddSheetChannel.setMessageHandler(nil)
    }
    let goToDetailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.goToDetail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToDetailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.goToDetail(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToDetailChannel.setMessageHandler(nil)
    }
    let toggleFavoriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.toggleFavorite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleFavoriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let isFavoriteArg = args[1] as! Bool
        do {
          try api.toggleFavorite(id: idArg, isFavorite: isFavoriteArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toggleFavoriteChannel.setMessageHandler(nil)
    }
    let toggleDoneChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.TaskHostApi.toggleDone\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleDoneChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let isDoneArg = args[1] as! Bool
        do {
          try api.toggleDone(id: idArg, isDone: isDoneArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toggleDoneChannel.setMessageHandler(nil)
    }
  }
}
