# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'AddToAppSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddToAppSample
  install_all_flutter_pods(flutter_application_path)

  target 'AddToAppSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AddToAppSampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
